/********************************************************************************
 * Copyright (c) 2026 Fraunhofer ISE
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 ********************************************************************************/

plugins {
    id 'application'
}

dependencies {
    implementation project(':abstract-controllablesystem')
    implementation project(':lpc-controllablesystem')
    implementation project(':lpp-controllablesystem')

    // https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
    implementation 'ch.qos.logback:logback-classic:1.5.32'
}

application {
    mainClass = 'org.openmuc.jeebus.usecase.powerlimitation.controllablesystem.demo.Main'
}
